# Generated by Django 5.1.3 on 2024-11-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='resolution_notes',
        ),
    ]
